export const REGISTER_SUCCESSFULLY = "REGISTER_SUCCESSFULLY";
export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const FORGOT_SUCCESSFULLY = "FORGOT_SUCCESSFULLY";
export const RESET_SUCCESSFULLY = "RESET_SUCCESSFULLY";
export const GET_USER_SUCCESSFULLY = "GET_USER_SUCCESSFULLY";